name: holodex_notifier
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.21.2
  cached_network_image: ^3.3.1
  collection:
  dio:
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences:
  flutter_secure_storage: ^9.2.4
  flutter_local_notifications: ^19.1.0
  flutter_cache_manager: ^3.3.2
  timezone: ^0.10.0 
  connectivity_plus:
  logger:
  flutter_background_service:
  android_alarm_manager_plus: ^4.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  intl:
  synchronized: ^3.1.0
  stream_transform: ^2.1.0 
  url_launcher: ^6.3.0
  android_intent_plus: ^5.0.1
  font_awesome_flutter: ^10.7.0
  share_plus: ^10.1.4
  file_picker: ^10.1.2
  timeago: ^3.6.1
  device_info_plus: ^11.3.3
  permission_handler: ^12.0.0+1 
  archive: ^4.0.6
  disable_battery_optimization:
    git:
      url: https://github.com/pvsvamsi/Disable-Battery-Optimizations
      ref: 3bd744d03c416859bbaedecd61c1c11fc022ed75

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  drift_dev: ^2.17.0
  mockito: ^5.4.5
  riverpod_test: ^0.1.6

dependency_overrides:
  analyzer: ^6.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/config/ 

android:
  minSdkVersion: 27
  targetSdkVersion: 33